# -*- coding: utf-8 -*-
"""10-02-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrDyJNmFFajOOmk9eU99pOA6HY9EAH-C
"""

!pip install PyPDF2

import PyPDF2
from PyPDF2 import PdfFileReader

PyPDF2.__version__

import PyPDF2, urllib , nltk
from io import BytesIO
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

#Reading the PDF
wFile = urllib.request.urlopen('http://www.udri.org/pdf/02%20working%20paper%201.pdf')
pdfreader = PyPDF2.PdfReader(BytesIO(wFile.read()))

#extracting page 2 of the docuemnt
pageObj = pdfreader.pages[2]
page2 = pageObj.extract_text()
#Cleaning the text
punctuations = ['(',')',';',':','[',']',',','...','.']
tokens = word_tokenize(page2)
stop_words = stopwords.words('english')
keywords = [word for word in tokens if not word in stop_words and not word in punctuations]

keywords

name_list = list()
check =  ['Mr.', 'Mrs.', 'Ms.']
for idx, token in enumerate(tokens):
    if token.startswith(tuple(check)) and idx < (len(tokens)-1):
        name = token + tokens[idx+1] + ' ' +  tokens[idx+2]
        name_list.append(name)
print(name_list)

wFile.close()

#Creating a pdf file object
pdf = open("/content/file1.pdf","rb")
#creating pdf reader object
pdf_reader = PyPDF2.PdfReader(pdf)
#checking number of pages in a pdf file
print("Number of pages:",len(pdf_reader.pages))
#creating a page object
page = pdf_reader.pages[1]
#finally extracting text from the page
print(page.extract_text())
#closing the pdf file
pdf.close()

