# -*- coding: utf-8 -*-
"""4-02-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb2c0oG6Fxx5dSI2REQ6lZRDMzjrdfIQ
"""

!pip install emot

#create sample text data with emoji
text1 = "What are you saying😂 . I am the boss😎, and why are you so😣 "

#https://emojipedia.org
#https://emojijoy.com/
#https://unicode.org/emoji/charts/full-emoji-list.html
#https://apps.timwhitlock.info/emoji/tables/unicode
#Windows+. -> display emoji

import re
from emot.emo_unicode import UNICODE_EMOJI
from emot.emo_unicode import EMOTICONS_EMO

# Function for converting emojis into word
def converting_emojis(text):
    for emot in UNICODE_EMOJI:
        text = text.replace(emot, "_".join(UNICODE_EMOJI[emot].replace(",","")\
                                           .replace(":","").split()))
    return text
converting_emojis(text1)

def emoji_removal(string):

    emoji_unicodes = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols
                               u"\U0001F680-\U0001F6FF"  # transport
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"
                               u"\u3030"
                               "]+", flags=re.UNICODE)

    return emoji_unicodes.sub(r'', string)
emoji_removal(text1)

