# -*- coding: utf-8 -*-
"""7-02-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PbBpWNt0_V-5x8-3v8WNPhzmERr6IPw
"""

Text = "I am learning NLP"

# Importing the library
import pandas as pd
# Generating the features
pd.get_dummies(Text.split())

text = ["i love NLP and i will learn NLP in 2month"]
# single characters are ignored by count vectorizer

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(text)
vector = vectorizer.transform(text)

print(vectorizer.vocabulary_)
print(vector.toarray())

CountVectorizer?

df = pd.DataFrame(data=vector.toarray(), columns=vectorizer.get_feature_names_out() )
df

text = 'I am learning NLP'

from textblob import TextBlob
#For unigram : Use n = 1
TextBlob(text).ngrams(1)

#For Bigram : For bigrams, use n = 2
TextBlob(text).ngrams(2)

TextBlob(text).ngrams(3)

TextBlob(text).ngrams(4)

