# -*- coding: utf-8 -*-
"""FakeNewsDetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFL2e-E1EztpdBN-7JnJNnmQU0eLmJQR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/fake_news.csv')
data.head()

data.shape

data.info()

data.isna().sum()

data = data.drop(['id'], axis = 1)

data = data.fillna('')

data['content'] = data['author']+' '+data['title']+' '+data['text']

data = data.drop(['author', 'title', 'text'], axis=1)

data.head()

# Convert to lowercase
data['content'] = data['content'].apply(lambda x: " ".join(x.lower() for x in x.split()))

data['content'] = data['content'].str.replace('[^\w\s]','')

from nltk.corpus import stopwords
stop  = stopwords.words('english')
data['content'] = data['content'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

from nltk.stem import WordNetLemmatizer
from textblob import Word
data['content'] = data['content'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
data['content'].head()

X=data['content']
y=data['label']

from sklearn.model_selection import train_test_split

# splitting into training and testing data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=45, stratify=y)

#validate the shape of train and test dataset
print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

