# -*- coding: utf-8 -*-
"""Gemini_AI_Image_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dCFzSEaKaqDSJ42VIHXQsSu9AMKdSgg
"""

import google.generativeai as genai
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

import pathlib
import textwrap
from IPython.display import display, Markdown
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

import PIL.Image
img = PIL.Image.open('/content/image1.jpg')
img
model = genai.GenerativeModel('gemini-1.5-flash')
response = model.generate_content(["Write a short, engaging blog post based on this picture.  It should include a description of the meal in the photo and talk about my journey meal prepping.", img],
stream=True)
response.resolve()

to_markdown(response.text)

response = model.generate_content(["Generate an accurate caption for this image.", img])
print(response.text)

